# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CC 22 Point 3
author: the-intern
logo: images/pycode.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  # Online location of your book
  url: https://github.com/the-intern/cc22-3-book
  # Optional path to your book, relative to the repository root
  path_to_book: cc22-point-3/helpers
  # repo branch to be used when creating links(optional)
  branch: main

# ===========
# ==thebe?===
launch_buttons:
  thebe: true
  binderhub_url: "https://mybinder.org"  # BinderHub
  colab_url: "https://colab.research.google.com"

# ===========
# eliminated several errors shown with myst-nb material
#  in layout.md and hidden.md
myst_enable_extensions:
  extensions: ["myst_nb"]

# ===========

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
